# -*- coding: utf-8 -*-
"""reducer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YzJ-vUsO5VYCyMrfPMow3s2IdxXkyQ0i
"""

from operator import itemgetter
import sys

current_word = None  # Inicializa la variable para el palabra actual
current_count = 0  # Inicializa la variable para el conteo actual
word = None  # Inicializa la variable para la palabra

# input comes from STDIN
for line in sys.stdin:  # Itera sobre las líneas de entrada de la entrada estándar
    # remove leading and trailing whitespace
    line = line.strip()
    line = line.lower()  # Convierte la línea a minúsculas

    # parse the input we got from mapper.py
    word, count = line.split('\t', 1)  # Divide la línea en palabra y conteo
    try:
      count = int(count)
    except ValueError:
      # count was not a number, so silently
      # ignore/discard this line
      continue

    # this IF-switch only works because Hadoop sorts map output
    # by key (here: word) before it is passed to the reducer
    if current_word == word:  # Compara la palabra actual con la palabra anterior
        current_count += count  # Si son iguales, suma el conteo al conteo actual
    else:
        if current_word:
            # write result to STDOUT
            print ('%s\t%s' % (current_word, current_count))  # Imprime la palabra anterior y su conteo
        current_count = count  # Restablece el conteo actual
        current_word = word  # Establece la palabra actual como la nueva palabra

# do not forget to output the last word if needed!
if current_word == word:
    print( '%s\t%s' % (current_word, current_count))  # Imprime la última palabra y su conteo
