# Configuración del Agente para monitorización de un directorio

#Definición del agente: nombre y componentes
Agente_Dir.sources  = s1  
Agente_Dir.sinks    = k1  
Agente_Dir.channels = c1  
   
#Configuración de propiedades Source
Agente_Dir.sources.s1.type              = spooldir
Agente_Dir.sources.s1.spoolDir          = /tmp/logs
Agente_Dir.sources.s1.basenameHeader    = true
Agente_Dir.sources.s1.basenameHeaderKey = fileName

# Configuración de propiedades del canal
Agente_Dir.channels.c1.type    = memory

# Configuración de propiedades del sink
Agente_Dir.sinks.k1.type                   = hdfs
Agente_Dir.sinks.k1.hdfs.path              = /flume/events/%y-%m-%d/%H/
Agente_Dir.sinks.k1.hdfs.filePrefix        = %{fileName}
Agente_Dir.sinks.k1.hdfs.fileType          = DataStream
Agente_Dir.sinks.k1.hdfs.useLocalTimeStamp = true

#Vinculación de source y sink al canal creado
Agente_Dir.sources.s1.channels = c1
Agente_Dir.sinks.k1.channel    = c1
