# Configuración del Agente para monitorización de archivos

#Definición del agente: nombre y componentes
Ag_Monitor.sources  = s1  
Ag_Monitor.sinks    = k1  
Ag_Monitor.channels = c1  
   
#Definición de propiedades Source
Ag_Monitor.sources.s1.type    = exec
Ag_Monitor.sources.s1.command = tail -F /tmp/log.txt
Ag_Monitor.sources.s1.shell   = /bin/bash -c

# Configuración de propiedades del canal
a1.channels.c1.type = memory

# Configuración de propiedades del sink
a1.sinks.k1.type = logger

# Vinculación de source y sink al canal creado
Ag_Monitor.sources.s1.channels = c1
a1.sinks.k1.channel            = c1  
   


