# Plantilla para la definición de agentes Flume

# Definición de sources, channels y sinks
# Agente basico con un unico source y sink
<Agent>.sources  = <Source>
<Agent>.sinks    = <Sink>
<Agent>.channels = <Channel1> <Channel2>

# Propiedades del source
<Agent>.sources.<Source>.<someProperty> = <someValue>

# Propiedades del canal/es
<Agent>.channel.<Channel>.<someProperty> = <someValue>
...

# Propiedades del sink
<Agent>.sources.<Sink>.<someProperty> = <someValue>
...

# Vincular source al canal/es correspondiente
<Agent>.sources.<Source>.channels = <Channel1> <Channel2> ...

# Vincular sink al canal/es correspondiente
<Agent>.sinks.<Sink>.channel = <Channel1>



